name: llm

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - cudatoolkit=11.8  
  - pip
  - h5py
  - numpy
  - sox 
  - libsndfile
  - pip:
    - torch==2.0.0 
    - torchvision
    - transformers 
    - transforms3d
    - accelerate   
    - tensorboard
    - matplotlib
    #- tqdms
    - einops
    - scikit-learn
    - librosa
    - pandas
    - omegaconf
    - Cython
    - pyyaml
    - ConfigArgParse
    - easydict
    - rich
    - ffmpeg-normalize
    - blobfile
